
AllCops:
  NewCops: enable
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false