# Autogenerated!
# msgfmt -o /opt/foreman_plugins/foreman_auth_ldap_fix/locale/ru/LC_MESSAGES/foreman_auth_ldap_fix.mo /opt/foreman_plugins/foreman_auth_ldap_fix/locale/ru/foreman_auth_ldap_fix.po
_("All Hosts")
